import { ProductType } from "../types/product";

export const productsMock: ProductType[] = [

    {
        id: 1,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 2,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 3,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 4,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 5,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 6,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 7,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 8,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    },
    {
        id: 9,
        title: "Product 1",
        price: 25000,
        description: "a;lsdjf;laskd kajhsflkjashdlfkj Kalsdkfhlakjsdhfjkh",
        bestSeller: true,
        isNew: true,
        discount: 10,
        images: [''],
        quantity: 11,
    }
]